version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis-email
    

  api:
    build: .
    container_name: email-api
    command: node server.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: .
    container_name: email-worker
    command: node src/workers/email.worker.js
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
